apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-app
  template:
    metadata:
      labels:
        app: city-app
    spec:
      containers:
        - name: city-lib-container
          image: kalinic/city_lib:latest
          ports:
            - containerPort: 9001
          env:
            - name: CENTRAL_HOST
              value: central-app-service
        - name: postgres-db-container
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: city
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: root
          ports:
            - containerPort: 5432
