apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-bg
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-bg"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-bg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-ns
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-ns"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-ni
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-ni"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-ni
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
